export const FETCH_PRODUCT_CATEGORY = "FETCH_PRODUCT_CATEGORY";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const USER_DETAILS = "USER_DETAILS";
export const USER_LOGOUT = "USER_LOGOUT";
export const LOADING = "LOADING";
